services:
  pocketbase:
    build: ./services/pocketbase
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./services/pocketbase/pb_data:/pb/pb_data
    restart: unless-stopped
    env_file:
      - .env.local

  galene:
    build: ./services/galene
    container_name: galene
    ports:
      - "8443:8443"
      - "10000-10020:10000-10020/udp"
    volumes:
      - ./services/galene/groups:/galene/groups
      - ./services/galene/data:/galene/data
    environment:
      - GALENE_INSECURE=1
      - GALENE_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
